### ISSUE TITLE
Write email log in custom file

### ISSUE THREAD

**Issue by heavybeard** [salcode/stop-emails#10]
Hi @salcode,
great plugin, useful for me for development environments.

But, I think the `file_put_contents` on a custom file should be a useful option to add.
I would use a custom email_sent.log file instead of `error_log` function.

Are you still supporting this plugin?

**Comment by salcode** [comment]
Hi @heavybeard, I'm glad you're finding the plugin useful.

I can definitely see how writing the email to a custom file would be useful but one of my goals is to keep this plugin as simple as possible so I don't think that is something I want to add at this time. There is a hook in the plugin called [fe_stop_emails_log](https://github.com/salcode/stop-emails/blob/master/stop-emails.php#L72), which can be used to extend this plugin and log information somewhere else.

## Untested Code

Off the top of my head, I think something like this should work:

```
add_action( 'fe_stop_emails_log', 'gh_sei_10_log', 10, 1 );

function gh_sei_10_log( $email ) {
    file_put_contents( 'email_sent.log', print_r( $email, true ) );
}
```

## Example of Using the fe_stop_emails_log Hook

I actually started a plugin here on GItHub to log emails to a WordPress Custom Post Type called [Stop Emails Logger](https://github.com/salcode/stop-emails-logger) but I'm not actively working on that plugin.

## Another Option to Capture Emails

If I really want to test emails, I've found [MailCatcher](https://mailcatcher.me/) to be a great tool.  I use [VVV](https://salferrarello.com/vagrant-vvv-setup-wordpress/) for development and MailCatcher comes pre-installed.

**Comment by heavybeard** [comment]
Wow, thanks for your fast and complete support.
I tried the untested code and work like a charm with the ABSPATH default wordpress constant.

Thank you very much, again.

**Comment by salcode** [comment]
Glad it worked out. Good call on adding the ABSPATH.

Cheers.
