### ISSUE TITLE
What should the logging behavior be when run from WP CLI?

### ISSUE THREAD

**Issue by salcode** [salcode/stop-emails#15]
As @mitchelldmiller bring up in [this comment](https://github.com/salcode/stop-emails/issues/14#issuecomment-366066850)

When [WP CLI](http://wp-cli.org/) is used to run code that tries to send an email

> The screen fills with error_log output.

He suggests

> You might want to replace the error_log() if WP-CLI is active.

**Comment by mitchelldmiller** [comment]
Suggestion:
```php
 public function log_to_php_error_log( $mock_email ) {
      if ( $this->should_emails_be_logged_to_php_error_log() ) {
         $text = $this->mock_email_to_text( $mock_email );
         if ( defined( 'WP_CLI' ) && WP_CLI ) {
            error_log( 'Stop Emails: suppressing error log' );
         } else {
            error_log( $text );
         } // end if WP-CLI
      }
   } 
```

**Comment by salcode** [comment]
Since ultimately I decided not to introduce any changes based on this issue, I'm going to mark this as closed.
