### ISSUE TITLE
Update PHPMailer code in a backwards compatible way for WordPress 5.5

### ISSUE THREAD

**Issue by salcode** [salcode/stop-emails#18]
I received the following email regarding the upcoming WordPress 5.5 release

> A plugin you have commit access to has been flagged as using the PHPMailer library. This library has been updated in the upcoming WordPress release (5.5) from version 5.2.27 to version 6.1.6. This is a major update to the library with several backward compatibility breaks. The target date for the release of WordPress 5.5 is 2020-08-11.
> 
> Affected plugin(s):
> 
> * https://wordpress.org/plugins/stop-emails
> 
> Here are some rough code examples that may have matched in your plugin(s):
> 
> * $mailer = new PHPMailer();
> * include ABSPATH . WPINC . 'class-phpmailer.php'
> 
> Trunk always contains the bleeding edge, unreleased WordPress code that is being worked on for the next release (in this case, 5.5). Please take the time to test your plugin(s) against trunk to ensure your users will not experience any issues or unintended behavior after this update.
> 
> * A full list of changes to the library: https://make.wordpress.org/core/2020/07/01/external-library-updates-in-wordpress-5-5-call-for-testing/
> * The relevant changesets updating PHPMailer in WordPress: https://core.trac.wordpress.org/log/?revs=48033-48036,48058
> * Official upgrade guide – Upgrading from PHPMailer 5.2 to 6.0: https://github.com/PHPMailer/PHPMailer/blob/master/UPGRADING.md#other-upgrade-changes

We need to test the plugin with WordPress 5.5 and make any necessary adjustments

**Comment by salcode** [comment]
The following changes appear to be relevant to this plugin and are from the post [External Library updates in WordPress 5.5: call for testing](https://make.wordpress.org/core/2020/07/01/external-library-updates-in-wordpress-5-5-call-for-testing/).

**Note**: All of these changes have been made in a backwards compatible way, so if we make not changes here to the Stop Emails plugin there should be no change in functionality (_other_ than deprecation notices will be thrown).

1. `wp-includes/class-phpmailer.php` has been moved to `wp-includes/PHPMailer/PHPMailer.php`
2. loading the above file from the new location means we also need to load `wp-includes/PHPMailer/Exception.php`
3. The `PHPMailer` class now has a namespace so we'll need to add the line `
use PHPMailer\PHPMailer\PHPMailer;`

## Recommendation

Make no changes at this time.

If we make the above changes, e.g. change the file we load, this plugin will no longer work on WordPress version prior to 5.5.

Therefore it makes sense to keep using the deprecated methods, which will allow the plugin to work on WordPress 5.5 and older versions. At some point in the future, we will make these changes and drop support for versions `<5.5`.

**Comment by jaredatch** [comment]
I'd humbly request/suggest version check so error logs don't fill up with deprecated notices 😀

https://github.com/awesomemotive/WP-Mail-SMTP/blob/master/src/Core.php#L779

**Comment by salcode** [comment]
Clearly my original thoughts in this issue were too narrowly focused on my own use of this plugin and I apologize for this.

Thank you @jaredatch for the example code that I can use in crafting the conditional clause.

**Comment by salcode** [comment]
My first thought it to conditionally load different files (one for pre WP 5.5 and one for WP 5.5+) however I enjoy that `stop-emails.php` can be used as a single file (I find this is particularly useful in dropping the single file in the `mu-plugins` directory).

This line seems to be the challenge

```
class Fe_Stop_Emails_Fake_PHPMailer extends PHPMailer {
```

since on pre 5.5 we'll be extending `PHPMailer` and on 5.5+ we'll be extending `PHPMailer\PHPMailer\PHPMailer`.

Right now I'm playing with the idea of creating a subclass of `PHPMailer` (or `PHPMailer\PHPMailer\PHPMailer`) and then making `Fe_Stop_Emails_Fake_PHPMailer` a subclass of this new intermediary subclass.

**Comment by jaredatch** [comment]
Awesome, thanks for the update :)
