### ISSUE TITLE
Add link to "Known Incompatible Plugins" in readme.txt

### ISSUE THREAD

**Issue by salcode** [salcode/stop-emails#21]
Add a link to the wiki page [Known Incompatible Plugins](https://github.com/salcode/stop-emails/wiki/Known-Incompatible-Plugins) in the `readme.txt` file

> I gave this a try and found it didn’t work for me. I came back and looked at the support threads and found there’s a list of incompatible plugins on github.
>
> Please consider adding that – or at least a link to it – in the description and/or the FAQ.

from the original support thread [List of incompatibilities](https://wordpress.org/support/topic/list-of-incompatibilities/) on wordpress.org from @jodzeee

**Comment by mitchelldmiller** [comment]
Hello @salcode:
Stop-emails has been on my [Quick Mail incompatibility list](https://mitchelldmiller.github.io/quick-mail-wp-plugin/#incompatible) for a couple of years `:)`

Best wishes,
Mitchell

**Comment by salcode** [comment]
Hi @mitchelldmiller,

Thanks for the reminder. I know we discussed your Quick Mail plugin in the past but I had failed to include it on the [Known Incompatible Plugins](https://github.com/salcode/stop-emails/wiki/Known-Incompatible-Plugins) list - my apologies.

I've updated the list now to include Quick Mail.

Thanks.
