### ISSUE TITLE
Allow password reset emails through

### ISSUE THREAD

**Issue by NickGreen** [salcode/stop-emails#25]
Would like to be able to allow users to still be able to reset their passwords using the 'Reset my password' link on the WP login page.

Having a conditional that allows an email to go through could be useful for the whitelist suggestion in your support requests, so I figured I'd spitball here.

One method I though of was to try and add a conditional to your `send()` function, [around line 68](https://github.com/salcode/stop-emails/blob/master/stop-emails.php#L68). Something like this:

```PHP
if ( strstr( $this->Subject, 'Password Reset Request') ) {
	return $this->postSend();
}
```

The conditional works, but still nothing is sending, AFAICT.

At one point, you suggested to c[onditionally use the original phpMailer here](https://wordpress.org/support/topic/how-to-disable-temporarily/#post-6814641), but I'm still wrapping my head around where that is called. Let me know if you have any ideas for how I could implement this.

**Comment by NickGreen** [comment]
I see now that on `plugins_loaded`, you are replacing the PHPMailer object with your own: https://github.com/salcode/stop-emails/blob/b225bd1ba6dcbeff80d443064d7f10d5864f9d40/stop-emails.php#L149-L153

So now I'm thinking we could add in a block of code in your `send()` function that actually _does_ send an email. Like, copy the real `send()` function and make it available, conditionally.

**Comment by NickGreen** [comment]
Thinking about possibly not using this plugin, and instead using this code, which appears to test well so far, and is significantly simpler than this plugin:

```PHP
add_filter( 'wp_mail', function( $args ) {
	if (! strstr( $args['subject'], 'Password Reset Request') ) {
		error_log("Stopped outgoing email");
		unset ( $args['to'] );
	}
    return $args;
});
```

**Comment by salcode** [comment]
Hey @NickGreen,

I agree with you assessment that the current way this plugin is built is not setup to conditionally allow some emails through while not others.

While I hear you that filtering emails could be useful in some cases, that isn't a feature I'm interested in adding at this time.

For your situation, I like your solution of applying a filter to `wp_mail` 👍

I appreciate you sharing all the details around your thinking about possible solutions, I suspect this thread may help others in the future.

**Comment by NickGreen** [comment]
> While I hear you that filtering emails could be useful in some cases, that isn't a feature I'm interested in adding at this time.

Roger that. Feel free to close this issue out then, as needed.
