### ISSUE TITLE
Translate to Italian / Traduci in italiano

### ISSUE THREAD

**Issue by salcode** [salcode/stop-emails#6]
Here is my attempt at translation to Italian.  If anyone has corrections, I would appreciate them.

Qui è il mio tentativo di traduzione in italiano. Se qualcuno ha correzioni, io li apprezzare. (Google Translate)

> Stop Emails

Smettere di email

> Email Logging

Email registrazione

> Log Emails

Log-mail

> The Stop Emails plugin has the option to log stopped emails to the PHP error log.

La Stop Emails plugin ha la possibilità di accedere email fermati nel lob degli errori di PHP.

> Disable Logging

Disattivare la registrazione

> Log stopped emails to the PHP Error Log

Entra fermò e-mail nel lob degli errori di PHP

> To: 

Destinatario: 

> From: 

Mittente: 

> Subject: 

Argomento: 

> Logging Disabled Emails

Registrazione email disabili

> Emails Disabled

Email per disabili

> The Stop Emails plugin is currently active, which will prevent any emails from being sent.  

La Stop Emails plugin è attualmente attiva, che impedirà qualsiasi e-mail vengano inviati. 

> To send emails, disable the plugin.

Disattivare il plugin per inviare e-mail

> Stops outgoing emails sent using wp_mail() function

Ferma messaggi di posta elettronica in uscita inviati utilizzando la funzione wp_mail()

**Comment by ilGhera** [comment]
Nice try ;-)

[stop-emails-it_IT.txt](https://github.com/salcode/stop-emails/files/41003/stop-emails-it_IT.txt)

**Comment by salcode** [comment]
@ilGhera You are awesome.  Thank you.

Molto bene.  Grazie.

**Comment by salcode** [comment]
Version 1.1.0 with Italian Translation is now available at https://wordpress.org/plugins/stop-emails/

Thanks you, @ilGhera
